# default haproxy listen directive for our http services
http_service_default_listen: &http_service_default_listen
  - mode http
  - stats enable

  - option httpchk /health
  - http-check expect string OK

# list the services to connect
services:
  - name: sherlock
    local_port: 3212
    server_options: check inter 2000 rise 3 fall 2
    default_servers:
      - 'localhost:8423'
    discovery:
      method: zookeeper
      path: /airbnb/service/sherlock
      hosts:
        - zk0.sys.airbnb.com
    listen:
      - *http_service_default_listen

  - name: search
    local_port: 3213
    server_options: check inter 2000 rise 3 fall 2
    default_servers:
      - 'localhost:8422'
    discovery:
      method: zookeeper
      path: /airbnb/service/search
      hosts:
        - zk0.sys.airbnb.com
    listen:
      - *http_service_default_listen

# settings for haproxy including the global config
haproxy:
  reload_command: "sudo service haproxy reload"
  config_file_path: "/usr/local/etc/haproxy.conf"
  global:
    - daemon
    - user haproxy
    - group haproxy
    - pidfile 
    - maxconn 4096
    - log     127.0.0.1 local0
    - log     127.0.0.1 local1 notice
    - \#debug
    - \#quiet
    - \#chroot /usr/share/haproxy

  defaults:
    - log global
    - option   dontlognull
    - maxconn  2000
    - retries  3
    - timeout  connect 5000
    - timeout  client  50000
    - timeout  server  50000
    - option   redispatch
    - balance  roundrobin

# the synapse config; lists program options
synapse:
  self_check_port: 3210
  self_check_proxy_port: 3211
  zk_servers:
    - 'localhost:2181'
